CREATE DATABASE FoodOrder
USE FoodOrder
CREATE TABLE DanhMucMonAn(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	TenDanhMuc NVARCHAR(100) NOT NULL,
	NgayTao DATETIME NOT NULL,
	TrangThai INT NOT NULL
)

CREATE TABLE MonAn(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	IdDanhMuc UNIQUEIDENTIFIER REFERENCES dbo.DanhMucMonAn(Id) NOT NULL,
	HinhAnh NVARCHAR(MAX) NOT NULL,
	TenMon NVARCHAR(100) NOT NULL,
	GiaTien DECIMAL(20, 0) NOT NULL,
	MoTa NVARCHAR(MAX) NOT NULL,
	NgayTao DATETIME NOT NULL,
	TrangThai INT NOT NULL
)

CREATE TABLE Ban(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	TenBan INT NOT NULL,
	QRCode VARCHAR(MAX) NOT NULL,
	NgayTao DATETIME NOT NULL,
	TrangThai INT NOT NULL
)
ALTER TABLE dbo.Ban ADD Urll VARCHAR(MAX) NOT NULL

CREATE TABLE ChucVu(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	Ten NVARCHAR(50) NOT NULL,
	NgayTao DATETIME NOT NULL,
	TrangThai INT
)

CREATE TABLE NhanVien(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	IdChucVu UNIQUEIDENTIFIER REFERENCES dbo.ChucVu(Id) NOT NULL,
	HoTen NVARCHAR(50) NOT NULL,
	GioiTinh INT NOT NULL,
	NgaySinh DATE NOT NULL,
	Sdt VARCHAR(15) NOT NULL,
	TaiKhoan VARCHAR(50) NOT NULL,
	MatKhau VARCHAR(MAX) NOT NULL,
	NgayTao DATETIME NOT NULL,
	TrangThai INT NOT NULL
)

CREATE TABLE HoaDon(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	IdNhanVien UNIQUEIDENTIFIER REFERENCES dbo.NhanVien(Id) NOT NULL,
	IdBan UNIQUEIDENTIFIER REFERENCES dbo.Ban(Id) NOT NULL,
	Ma VARCHAR(30) NOT NULL,
	TongTien DECIMAL(20, 0) NOT NULL,
	NgayTao DATETIME NOT NULL,
	NgayThanhToan DATETIME NOT NULL,
	TrangThai INT NOT NULL
)

CREATE TABLE HoaDonChiTiet(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID() NOT NULL,
	IdHoaDon UNIQUEIDENTIFIER REFERENCES dbo.HoaDon(Id) NOT NULL,
	IdMonAn UNIQUEIDENTIFIER REFERENCES dbo.MonAn(Id) NOT NULL,
	SoLuong INT NOT NULL,
	GiaTien DECIMAL(20, 0) NOT NULL,
	NgayTao DATETIME NOT NULL,
	TrangThai INT NOT NULL
)



USE FoodOrder

SELECT * FROM dbo.ChucVu
INSERT INTO ChucVu (Ten, NgayTao, TrangThai)
VALUES (N'Quản lý', GETDATE(), 1)
INSERT INTO ChucVu (Ten, NgayTao, TrangThai)
VALUES (N'Nhân viên', GETDATE(), 1)

SELECT * FROM dbo.NhanVien

INSERT INTO NhanVien (IdChucVu ,HoTen, GioiTinh, NgaySinh, Sdt, TaiKhoan, MatKhau, NgayTao, TrangThai)
VALUES ('E7727574-07E0-46B4-86A7-E4931C9548EC' , N'Nguyễn Việt', 1, '2000-02-02', '0999999999', 'vietnt', '123456', GETDATE(), 1)

INSERT INTO NhanVien (IdChucVu ,HoTen, GioiTinh, NgaySinh, Sdt, TaiKhoan, MatKhau, NgayTao, TrangThai)
VALUES ('BB96B457-4C9E-4573-BC8A-E0F171F429E7' , N'Nguyễn Tuấn', 1, '2003-03-03', '0999999999', 'tuannv', '123456', GETDATE(), 1)



SELECT * FROM dbo.DanhMucMonAn
INSERT INTO DanhMucMonAn (TenDanhMuc, NgayTao, TrangThai) VALUES (N'Gà', GETDATE(), 1)

DELETE FROM dbo.DanhMucMonAn WHERE Id = 'B0759493-3B39-4141-AB82-19B874C53741'

UPDATE dbo.DanhMucMonAn SET TrangThai = 0 WHERE Id = '1ABC2454-42F3-431D-8832-C4C3FFDA48DC'


SELECT * FROM dbo.DanhMucMonAn
SELECT * FROM dbo.MonAn
INSERT INTO MonAn (IdDanhMuc, HinhAnh, TenMon, GiaTien, MoTa, NgayTao, TrangThai)
VALUES ('20B11E9A-D980-4955-B9A2-6AC900F08457', 'ccc.jpg', N'Gà rán KFC', 200000, N'Ngon', GETDATE(), 1)





SELECT * FROM Ban
INSERT INTO Ban(TenBan, QRCode, NgayTao, TrangThai) VALUES (N'Bàn 1', 'vvv.sss', GETDATE(), 1)

